name: Setup S3 Bucket Policy
description: This creates a S3 Bucket and configures it for static site hosting

inputs:
  bucket-name:
    description: 'Name of the bucket must be unqiue.'
    required: true

outputs:
  s3-bucket-url:
    description: 'S3 URL for created S3 bucket'
    value: ${{steps.S3BucketURL.s3-bucket-url}}

runs:
  using: 'composite'
  steps:
    # - run: aws s3api create-bucket --bucket ${{inputs.bucket-name}}
    #   shell: bash
    #   # TODO: make this action output the file.

    - name: Create Policy from template
      run: sed "s/{{bucket_name}}/${{inputs.bucket-name}}/" file://s3BucketPolicy.json  > "${{input.bucket-name}}-policy.json"
      shell: bash
    - name: Log file
      run: cat "${{input.bucket-name}}-policy.json"
      shell: bash

    - name: Set S3 Bucket Policy
      run: aws s3api put-bucket-policy --bucket ${{inputs.bucket-name}} --policy file://${{inputs.bucket-name}}-policy.json
      shell: bash

    - name: Setup Bucket for Static Site Hosting
      run: aws s3api put-bucket-website --bucket ${{inputs.bucket-name}} --policy file://website-configuration.json
      shell: bash

    - name: Get Bucket Website
      run: aws s3api put-bucket-website --bucket ${{inputs.bucket-name}} --website-configuration file://website-configuration.json
      shell: bash

    - id: S3BucketURL
      run: echo "s3-bucket-url=s3://{{inputs.bucket-name}}"
      shell: bash
