name: Repo Setup
on:
  workflow_dispatch:
    inputs:
      repo-name:
        required: true
        description: Name of the Repo To Setup
      bucket-name:
        required: true
        description: S3 Bucket Name to Use
      aws-access-id:
        description: Access ID for AWS account
      aws-secret-access-key:
        description: Access Key for AWS account
jobs:
  setup-s3-bucket:
    # af
    runs-on: ubuntu-latest
    steps:
      # Setup R
      - uses: actions/checkout@v3
        name: Checkout Repository

      # Setup S3 bucket
      - id: SetupS3Bucket
        uses: ./.github/actions/SetupAWSBucket
        with:
          bucket-name: ${{inputs.bucket-name}}
        env:
          AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_EC2_METADATA_DISABLED: true

      - run: echo ${{steps.SetupS3Bucket.outputs.s3-bucket-url}}

  setup-github-repo:
    runs-on: ubuntu-latest
    needs: setup-s3-bucket
    steps:
      # Setup
      - uses: actions/checkout@v3
        name: Checkout Repository

      - uses: actions/download-artifact@v3
        with:
          name: ${{inputs.bucket-name}}-policy.json
      - run: echo ${{inputs.bucket-name}}-policy.json
      - run: ls

      - run: echo ${{needs.setup-s3-bucket.outputs.s3-bucket-url}}
  # Set Secrets
  # Configure S3 variables.
  # Create a S3 bucket and configure permissions.
# aws s3api  --profile jayant-hcode get-bucket-website --bucket devop-test-bucket1
# aws s3api  --profile jayant-hcode get-bucket-website --bucket devop-test-bucket1
