name: Repo Setup
on:
  workflow_dispatch:
    inputs:
      repo-name:
        required: true
        description: Name of the Repo To Setup
      bucket-name:
        required: true
        description: S3 Bucket Name to Use
      aws-access-id:
        description: Access ID for AWS account
      aws-secret-access-key:
        description: Access Key for AWS account
jobs:
  setup-s3-bucket:
    # af
    runs-on: ubuntu-latest
    steps:
      # Setup R
      - uses: actions/checkout@v3
        name: Checkout Repository

      # Setup S3 bucket
      - id: SetupS3Bucket
        uses: ./.github/actions/SetupAWSBucket
        with:
          bucket-name: ${{inputs.bucket-name}}
        env:
          AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_EC2_METADATA_DISABLED: true

      # - run: echo ${{steps.SetupS3Bucket.outputs.s3-bucket-url}}

  setup-github-repo:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: setup-s3-bucket
    steps:
      # Setup
      - uses: actions/checkout@v3
        name: Checkout Repository
        with:
          token: ${{ secrets.JP_PERSONAL_ACCESS_TOKEN }}
          repository: jayant3110/template-vite-repo
          branch: main

      # Download Bucket Policy
      - uses: actions/download-artifact@v3
        with:
          name: ${{inputs.bucket-name}}-policy.json

      # Download Website Configuration
      - uses: actions/download-artifact@v3
        with:
          name: ${{inputs.bucket-name}}-website-configuration.json

      - name: Remove Git Folder
        run: rm -rf .git

      - name: Configure Git
        run: |
          git config --global user.email "github-actions"
          git config --global user.name "github-actions@github.com"

      - name: Init Git Repo, Add First Commit
        run: |
          git init
          git add .
          git commit -m 'First Commit From Workflow'

      - run: echo ${{github.repository_owner}}

      # Create Github repo and set secrets.
      - name: Create Repo ${{inputs.repo-name}}
        env:
          GH_TOKEN: ${{ secrets.JP_PERSONAL_ACCESS_TOKEN }}
        run: |
          gh repo create ${{inputs.repo-name}} --private --source=. --push
          gh secret set AWS_ACCESS_KEY_ID --body ${{ inputs.aws-access-id }} --app actions --repos jayant3110/${{inputs.repo-name}}
          gh secret set AWS_SECRET_ACCESS_KEY --body ${{ inputs.aws-secret-access-key }} --app actions --repos jayant3110/${{inputs.repo-name}}
          gh secret set DEV_S3_URL --body s3://${{ inputs.repo-name }} --app actions --repos jayant3110/${{inputs.repo-name}}
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/jayant3110/${{inputs.repo-name}}/actions/variables \
            -f name='DEV_S3_URL' \
            -f value=s3://${{inputs.bucket-name}}

      - name: Trigger Deploy on Dev Workflow
        run: gh workflow run Deploy.yml -R jayant3110/${{inputs.repo-name}} -F environment=Dev
        env:
          GH_TOKEN: ${{ secrets.JP_PERSONAL_ACCESS_TOKEN }}
