name: Repo Setup
on:
  workflow_dispatch:
    inputs:
      repo-name:
        required: true
        description: Name of the Repo To Setup
      bucket-name:
        required: true
        description: S3 Bucket Name to Use
      aws-access-id:
        description: Access ID for AWS account
      aws-secret-access-key:
        description: Access Key for AWS account
jobs:
  setup-s3-bucket:
    # af
    runs-on: ubuntu-latest
    steps:
      # Setup R
      - uses: actions/checkout@v3
        name: Checkout Repository

      # Setup S3 bucket
      - id: SetupS3Bucket
        uses: ./.github/actions/SetupAWSBucket
        with:
          bucket-name: ${{inputs.bucket-name}}
        env:
          AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_EC2_METADATA_DISABLED: true

      - run: echo ${{steps.SetupS3Bucket.outputs.s3-bucket-url}}

  setup-github-repo:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: setup-s3-bucket
    steps:
      # Setup
      - uses: actions/checkout@v3
        name: Checkout Repository

      # Download Bucket Policy
      - uses: actions/download-artifact@v3
        with:
          name: ${{inputs.bucket-name}}-policy.json

      # Download Website Configuration
      - uses: actions/download-artifact@v3
        with:
          name: ${{inputs.bucket-name}}-website-configuration.json

      - name: Remove Git Folder
        run: rm -rf .git

      - name: Init git
        run: git init

      - name: Add All
        run: git add .

      - name: Remove Git Folder
        run: git commit -m 'First Commit From Workflow'

      - name: Configure Git
        run: git config --global user.email "tester@hcode.tech"
      - run: git config --global user.name "Workflow User"

      # Create Github repo
      - name: Create Repo ${{inputs.repo-name}}
        env:
          GH_TOKEN: ${{ secrets.JP_PERSONAL_ACCESS_TOKEN }}
        run: gh repo create ${{inputs.repo-name}} --private --source=. --push

      # Set Secrets
      - run: gh secret set AWS_ACCESS_ID --body ${{ inputs.aws-access-id }} --app actions --repos jayant3110/${{inputs.repo-name}}
        env:
          GH_TOKEN: ${{ secrets.JP_PERSONAL_ACCESS_TOKEN }}

      - run: gh secret set AWS_ACCESS_SECRET_KEY --body ${{ inputs.aws-secret-access-key }} --app actions --repos jayant3110/${{inputs.repo-name}}
        env:
          GH_TOKEN: ${{ secrets.JP_PERSONAL_ACCESS_TOKEN }}

      # - run: echo ${{needs.setup-s3-bucket.outputs.s3-bucket-url}}
  # Set Secrets
  # Configure S3 variables.
  # Create a S3 bucket and configure permissions.
# aws s3api  --profile jayant-hcode get-bucket-website --bucket devop-test-bucket1
# aws s3api  --profile jayant-hcode get-bucket-website --bucket devop-test-bucket1
